training:
  dataset: 'cifar10'
  datadir: ${env:TORCHVISION_DATA_DIR}/{dataset}.var/{dataset}_torchvision/
  train_dataset: ${env:FFCV_DATA_DIR}/{dataset}/doubleImage_train.beton
  val_dataset: ${env:FFCV_DATA_DIR}/{dataset}/test.beton
  batch_size: 512
  epochs: 100
  lambd: 0.0078125
  projector_dim: 128
  seed: 42
  algorithm: 'ssl'
  model: 'resnet50proj'
  num_workers: 4
  ckpt_dir: ${env:CHECKPOINT_DIR}
  use_autocast: True
  log_interval: 100