training:
  dataset: 'cifar10'
  ffcv_datadir: /home/arnab39/scratch/krishna/dothework/ffcv
  train_data_fname: train.beton
  val_data_fname: test.beton
  batch_size: 512
  epochs: 200
  lambd: 0.0078125
  temperature: 0.1
  projector_dim: 1024
  momentum_tau: 0.01
  seed: 42
  algorithm: 'linear'
  model: 'resnet50feat'
  num_workers: 4
  ckpt_dir: 'checkpoints'
  use_autocast: True
eval:
  train_algorithm: 'ssl'
  epoch: 100
  use_precache: True