training:
  dataset: 'cifar10'
  ffcv_datadir: /home/mila/a/arnab.mondal/scratch/ffcv/ffcv_datasets
  train_data_fname: train.beton
  val_data_fname: test.beton
  # train_dataset: {ffcv_datadir}/{dataset}/{train_data_fname}
  # val_dataset: {ffcv_datadir}/{dataset}/{val_data_fname}
  batch_size: 512
  epochs: 200
  lambd: 0.0078125
  temperature: 0.1
  projector_dim: 128
  momentum_tau: 0.01
  seed: 42
  algorithm: 'linear'
  model: 'resnet50feat'
  num_workers: 4
  ckpt_dir: 'checkpoints'
  use_autocast: True
eval:
  train_algorithm: 'ssl'
  epoch: 100