training:
  dataset: 'cifar10'
  ffcv_datadir: /network/projects/_groups/linclab_users/ffcv/ffcv_datasets
  train_data_fname: doubleImage_train.beton
  val_data_fname: test.beton
  # train_dataset: {ffcv_datadir}/{dataset}/{train_data_fname}
  # val_dataset: {ffcv_datadir}/{dataset}/{val_data_fname}
  batch_size: 512
  epochs: 100
  spectral_loss_weight: 0.01
  hypersphere_radius: 0.3
  projector_dim: 128
  seed: 42
  algorithm: 'spectralReg'
  model: 'resnet50proj'
  num_workers: 4
  ckpt_dir: /network/projects/_groups/linclab_users/fastssl/checkpoints
  use_autocast: True
  log_interval: 100