training:
  dataset: 'cifar10'
  train_dataset: '/data/krishna/data/ffcv/cifar_train.beton'
  val_dataset: '/data/krishna/data/ffcv/cifar_test.beton'
  batch_size: 512
  epochs: 100
  lambd: 0.000158
  project_dim: 128
  seed: 42
  algorithm: 'ssl'
  model: 'resnet50M'
  num_workers: 4
  ckpt_dir: '/data/krishna/research/results/0321/001/checkpoints'
  use_autocast: True