training:
  dataset: cifar10
  datadir: /scratch/krishna/data/cifar
  train_dataset: /scratch/krishna/cache/data/ffcv/cifar10/cifar10_train.beton
  val_dataset: /scratch/krishna/cache/data/ffcv/cifar10/cifar10_test.beton
  batch_size: 512
  epochs: 100
  lambd: 0.1
  embed_dim: 1536 
  seed: 1
  algorithm: mae
  model: mae_vit
  num_workers: 8
  ckpt_dir: ./results/0118/edim/1536
  use_autocast: True
  num_augmentations: 2
  mask_ratio: 0.75
  train_interval: 10
logging:
  use_wandb: True
  wandb_project: fosssl 
